---
# For more information about default variables see:
# http://www.ansibleworks.com/docs/playbooks_variables.html#id26
#
# vim_config:
#   - "set tabstop=2"
#   - "set shiftwidth=2"
#   - "syntax enable"

# global vim configuration
vim_config: []