---

php_xdebug_key: PHPSTORM

php_repository: ppa:ondrej/php5-5.6
php_timezone: Europe/London

php_install:
  - php5
  - php5-xdebug
  - php5-curl
  - php5-gd
  - php5-mysql
  - php5-mcrypt
  - php5-memcache

php_configure:
  - file: /etc/php5/cli/php.ini
    values:
      - { section: date, key: date.timezone, value: '{{ php_timezone }}' }
  - file: /etc/php5/apache2/php.ini
    values:
      - { section: date, key: date.timezone, value: '{{ php_timezone }}' }
  - file: /etc/php5/mods-available/xdebug.ini
    values:
      - { section: date, key: date.timezone, value: '{{ php_timezone }}' }
      - { section: xdebug, key: xdebug.idekey, value: '{{ php_xdebug_key }}' }


php_config:
    - option: "error_reporting"
      section: "PHP"
      value: "E_ALL"
    - option: "display_errors"
      section: "PHP"
      value: "On"
    - option: "display_startup_errors"
      section: "PHP"
      value: "On"