---
# meta file for fail2ban
galaxy_info:
  author: Mischa ter Smitten
  company: Oefenweb.nl B.V.
  description: Set up fail2ban in Debian-like systems
  license: MIT
  min_ansible_version: 1.4
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - system
dependencies: []
