- name: install php5-fpm and all associated modules
  action: apt name={{ item }} state=installed
  with_items: 
    - php5-fpm
    - php5-common
    - php5-curl
    - php5-gd
    - php5-mysql


- name: service run php5-fpm 
  service: name=php5-fpm state=started 


- name: copy across php5-fpm.conf
  action: template src="{{ item }}" dest="/etc/php5/fpm/{{ item }}"
  with_items: 
     - php-fpm.conf
     - php.ini
  notify: 
    - restart php5-fpm service


- name: pool config
  action: template src="{{ item }}" dest="/etc/php5/fpm/pool.d/{{ item }}"
  with_items: 
     - www.conf
     # - www1.conf
     # - www2.conf
  notify: 
    - restart php5-fpm service